### ISSUE TITLE
Mix setup errors because of missing data file

### ISSUE THREAD

**Issue by jc00ke** [jeregrine/hex-search#1]
Hi there! I saw your blog post and wanted to contribute but experienced a little friction getting my environment set up, specifically when running `mix setup` I saw the following error:

```
Generated hex_docs_search app
The database for HexDocsSearch.Repo has been created

10:09:12.465 [info] == Running 20230707175953 HexDocsSearch.Repo.Migrations.CreatePackages.change/0 forward

10:09:12.467 [info] create table packages

10:09:12.467 [info] == Migrated 20230707175953 in 0.0s

10:09:12.471 [info] == Running 20230710200119 HexDocsSearch.Repo.Migrations.AddFTSIndex.up/0 forward

10:09:12.471 [info] execute "  CREATE VIRTUAL TABLE packages_index USING fts5(\n    doc,\n    title,\n    type,\n    ref UNINDEXED,\n    package_id UNINDEXED,\n  tokenize=\"porter\")\n"

10:09:12.471 [info] == Migrated 20230710200119 in 0.0s

10:09:12.472 [info] == Running 20230713153034 HexDocsSearch.Repo.Migrations.AddDocsConfig.change/0 forward

10:09:12.472 [info] alter table packages

10:09:12.472 [info] == Migrated 20230713153034 in 0.0s
** (File.Error) could not read file "/home/jesse/hex_docs.data": no such file or directory
    (elixir 1.14.5) lib/file.ex:358: File.read!/1
    (hex_docs_search 0.1.0) lib/hex_docs_search/hex/initial_data.ex:52: HexDocsSearch.Hex.InitialData.initialize!/0
    (elixir 1.14.5) lib/code.ex:1260: Code.require_file/2
    (mix 1.14.5) lib/mix/tasks/run.ex:144: Mix.Tasks.Run.run/5
    (mix 1.14.5) lib/mix/tasks/run.ex:84: Mix.Tasks.Run.run/1
    (mix 1.14.5) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.5) lib/mix/task.ex:479: Mix.Task.run_alias/6
    (mix 1.14.5) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```
Is there a stub file I could put in that path to continue?

Thanks!

**Comment by aayushmau5** [comment]
Seconded. 
Also, since it's sqlite, you could perhaps share the database file :thinking: @jeregrine

**Comment by jeregrine** [comment]
Wow that was fast lmao. I forgot that this was in there, gimme a few and I'll fix it.

**Comment by jeregrine** [comment]
Wanna

**Comment by jeregrine** [comment]
Wanna give it another shot?

**Comment by jc00ke** [comment]
![2023-08-08_12-56](https://github.com/jeregrine/hex-search/assets/18191/f90a1806-1fa3-4505-860b-315fd56571a9)

Looks to be working now! I think I'm downloading everything. I wonder if we need that much for dev?

**Comment by jeregrine** [comment]
Probably not! You can comment out the lines in the seeds.exs or change it
to download less. Once you do this once you won't have to do it again.

**Comment by jc00ke** [comment]
Thanks, I only installed the `@special_packages` but the results are not showing up when I type. I can open a separate issue for that.

**Comment by jeregrine** [comment]
@jc00ke Thanks! The data scraping tends to be fickle so please let me know what you see!
